name: turtle_messenger
description: New Messenger

publish_to: 'none'

version: 1.0.1+0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  amplify_auth_cognito: ^0.6.7
  amplify_api: ^0.6.7
  amplify_datastore: ^0.6.7
  amplify_flutter: ^0.6.7
  provider: ^6.0.3
  get_it: ^7.2.0
  cached_network_image: ^3.2.2
  image_picker: ^0.8.5+3
  dash_chat_2: ^0.0.14
  amplify_storage_s3: ^0.6.7
  photo_view: ^0.14.0
  http: ^0.13.5
  uuid: ^3.0.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/images/background.png
  uses-material-design: true