name: turtle_messenger
description: A new Messenger.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  amplify_auth_cognito: ^0.5.1
  amplify_api: ^0.5.1
  amplify_datastore: ^0.5.1
  amplify_flutter: ^0.5.1
  provider: ^6.0.3
  get_it: ^7.2.0
  flutter_native_splash: ^2.2.1
  cached_network_image: ^3.2.1
  pull_to_refresh: ^2.0.0
  image_picker: ^0.8.5+3
  dash_chat_2: ^0.0.6
  amplify_storage_s3: ^0.5.1
  photo_view: ^0.14.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#000000"